### ISSUE TITLE
subscription to instruments with '&' in 'symbol'

### ISSUE THREAD

**Issue by krishnavelu** [upstox/upstox-python#12]
subscription to instruments with '&' in 'symbol' give error.  Even after converting the & -> %26, The error is there this problem persists.

Unsubscribing - M%26M
WARNING:root:Cannot find symbol [nse_eq:m%26m] in master contract
Traceback (most recent call last):
File "D:\Projects\PTrade\test.py", line 162, in <module>
unsubscribe_to_all_nifty_stocks()
File "D:\Projects\PTrade\test.py", line 82, in unsubscribe_to_all_nifty_stocks
upstox.unsubscribe(upstox.get_instrument_by_symbol('NSE_EQ', n), LiveFeedType.Full)
File "C:\Program Files\Python36\lib\site-packages\upstox_api\api.py", line 594, in unsubscribe
raise TypeError("Required parameter instrument not of type Instrument")
TypeError: Required parameter instrument not of type Instrument

**Comment by Rahulzz** [comment]
We hope this message finds you well. We would like to inform you that the issue you reported is related to an outdated version of our API. As a result, we will be closing this issue since it is no longer valid. We understand the importance of staying up-to-date, so we strongly urge you to start planning your migration towards the latest version, v2, of our API. As part of this process, please be aware that our legacy v1 API and SDK are scheduled for deprecation soon.

Exciting news! We are thrilled to announce the release of our brand new V2 API version, bringing along various improvements and enhancements. You can access it at https://upstox.com/uplink/

To ensure a smooth transition, we recommend obtaining the most recent SDK (v2.0.0) by visiting: https://pypi.org/project/upstox-python-sdk/

For your convenience, all the necessary details regarding the API's functionalities can be found in our comprehensive API documentation: https://upstox.com/developer/api-documentation/

We sincerely appreciate your cooperation during this transition period, and our dedicated team is ready to assist you with any queries or support you may need while using the latest version of our API.

Thank you for being part of the Upstox community, and we look forward to providing you with an even better experience with our v2 API.

Best regards,
The Upstox Team
