### ISSUE TITLE
Is this project actively maintained? 

### ISSUE THREAD

**Issue by Code-Zed** [upstox/upstox-python#14]
Hi, 

I've noticed that there's no response to any of the issues on this project and have submitted a pull request (https://github.com/upstox/upstox-python/pulls) that hasn't been looked at yet.

I'm beginning to wonder if upstox is maintaining this project actively?
If yes please respond 
if not, I would be happy to maintain it . 

Thanks,

**Comment by debdipta** [comment]
Seems they won't maintain this project. Time to move out of upstox algo trading

**Comment by Rahulzz** [comment]
We hope this message finds you well. We would like to inform you that the issue you reported is related to an outdated version of our API. As a result, we will be closing this issue since it is no longer valid. We understand the importance of staying up-to-date, so we strongly urge you to start planning your migration towards the latest version, v2, of our API. As part of this process, please be aware that our legacy v1 API and SDK are scheduled for deprecation soon.

Exciting news! We are thrilled to announce the release of our brand new V2 API version, bringing along various improvements and enhancements. You can access it at https://upstox.com/uplink/

To ensure a smooth transition, we recommend obtaining the most recent SDK (v2.0.0) by visiting: https://pypi.org/project/upstox-python-sdk/

For your convenience, all the necessary details regarding the API's functionalities can be found in our comprehensive API documentation: https://upstox.com/developer/api-documentation/

We sincerely appreciate your cooperation during this transition period, and our dedicated team is ready to assist you with any queries or support you may need while using the latest version of our API.

Thank you for being part of the Upstox community, and we look forward to providing you with an even better experience with our v2 API.

Best regards,
The Upstox Team
