### ISSUE TITLE
Search instruments not returning correct results

### ISSUE THREAD

**Issue by vikassy** [upstox/upstox-python#18]
When searched from get_instrument_by_symbol, Nifty bank returns results. But when used search function it does not return the output. 

`ipdb>  o = u.get_instrument_by_symbol('NSE_INDEX', 'NIFTY_BANK')`
`ipdb> o`
Instrument(exchange=u'NSE_INDEX', token=u'', parent_token=None, symbol=u'nifty_bank', name=u'Nifty Bank', closing_price=27085.95, expiry=None, strike_price=None, tick_size=None, lot_size=None, instrument_type=u'INDEX', isin=None)
`ipdb> 
![screen shot 2019-02-03 at 6 14 25 pm](https://user-images.githubusercontent.com/1237354/52176903-94d9c200-27df-11e9-9e97-8c4a66d594af.png)
o = u.search_instruments('NSE_INDEX', 'NIFTY_BANK')`
`ipdb> o`
[]
![screen shot 2019-02-03 at 6 14 25 pm](https://user-images.githubusercontent.com/1237354/52176905-9f945700-27df-11e9-8a36-3b2e4c0cddd5.png)

**Comment by Rahulzz** [comment]
We hope this message finds you well. We would like to inform you that the issue you reported is related to an outdated version of our API. As a result, we will be closing this issue since it is no longer valid. We understand the importance of staying up-to-date, so we strongly urge you to start planning your migration towards the latest version, v2, of our API. As part of this process, please be aware that our legacy v1 API and SDK are scheduled for deprecation soon.

Exciting news! We are thrilled to announce the release of our brand new V2 API version, bringing along various improvements and enhancements. You can access it at https://upstox.com/uplink/

To ensure a smooth transition, we recommend obtaining the most recent SDK (v2.0.0) by visiting: https://pypi.org/project/upstox-python-sdk/

For your convenience, all the necessary details regarding the API's functionalities can be found in our comprehensive API documentation: https://upstox.com/developer/api-documentation/

We sincerely appreciate your cooperation during this transition period, and our dedicated team is ready to assist you with any queries or support you may need while using the latest version of our API.

Thank you for being part of the Upstox community, and we look forward to providing you with an even better experience with our v2 API.

Best regards,
The Upstox Team
