### ISSUE TITLE
 AttributeError: module 'websocket._ssl_compat' has no attribute 'ssl'

### ISSUE THREAD

**Issue by Multi360Degrees** [upstox/upstox-python#24]
Hello,

When i try to use the upstox using Recticulate package for Python for R , i get below error:
 
Error in py_module_import(module, convert = convert) : 
  AttributeError: module 'websocket._ssl_compat' has no attribute 'ssl'

Detailed traceback: 
  File "C:\PROGRA~3\ANACON~1\lib\site-packages\upstox_api\api.py", line 12, in <module>
    import websocket
  File "C:\PROGRA~3\ANACON~1\lib\site-packages\websocket\__init__.py", line 23, in <module>
    from ._app import WebSocketApp
  File "C:\PROGRA~3\ANACON~1\lib\site-packages\websocket\_app.py", line 36, in <module>
    from ._core import WebSocket, getdefaulttimeout
  File "C:\PROGRA~3\ANACON~1\lib\site-packages\websocket\_core.py", line 34, in <module>
    from ._handshake import *
  File "C:\PROGRA~3\ANACON~1\lib\site-packages\websocket\_handshake.py", line 30, in <module>
    from ._http import *
  File "C:\PROGRA~3\ANACON~1\lib\site-packages\websocket\_http.py", line 31, in <module>
    from ._socket import*
  File "C:\PROGRA~3\ANACON~1\lib\site-packages\websocket\_socket.py", line 30, in <module>
    from ._ssl_compat import *

Could you please help me?

**Comment by Rahulzz** [comment]
We hope this message finds you well. We would like to inform you that the issue you reported is related to an outdated version of our API. As a result, we will be closing this issue since it is no longer valid. We understand the importance of staying up-to-date, so we strongly urge you to start planning your migration towards the latest version, v2, of our API. As part of this process, please be aware that our legacy v1 API and SDK are scheduled for deprecation soon.

Exciting news! We are thrilled to announce the release of our brand new V2 API version, bringing along various improvements and enhancements. You can access it at https://upstox.com/uplink/

To ensure a smooth transition, we recommend obtaining the most recent SDK (v2.0.0) by visiting: https://pypi.org/project/upstox-python-sdk/

For your convenience, all the necessary details regarding the API's functionalities can be found in our comprehensive API documentation: https://upstox.com/developer/api-documentation/

We sincerely appreciate your cooperation during this transition period, and our dedicated team is ready to assist you with any queries or support you may need while using the latest version of our API.

Thank you for being part of the Upstox community, and we look forward to providing you with an even better experience with our v2 API.

Best regards,
The Upstox Team
