### ISSUE TITLE
Live Feed of NSE_EQ not giving proper data when bond is present

### ISSUE THREAD

**Issue by IosDeveloperHarsh** [upstox/upstox-python#37]
When i subscribe the Live Feed data for NSE EQ of "IDFCFIRSTB" IDFC First Bank Share, I am getting its bond equity feed not the share equity trading feed, this is happening because the bond is having same name and its showing as equity, Similarly i am facing this issue in the NTPC, REC etc the companies in which bond are issued i am not able to get there equity feeds. 

This is the feed i am receiving for IDFC FIRST BANK for NSE EXCHANGE
{
    timestamp: '1615975102000',
    exchange: 'NSE_EQ',
    symbol: 'IDFCFIRSTB',
      ltp: '10430',  <-  this price is of its listed bond not of the share
      close: '10500'  <-  this price is of its listed bond not of the share
  }

exchange | token | parent_token | symbol | name | closing_price | expiry | strike_price | tick_size | lot_size | instrument_type | isin |  
NSE_EQ | 11184 |   | IDFCFIRSTB | IDFC FIRST BANK LIMITED | 63.4 |   |   | 5 | 1 | EQUITY | INE092T01019
NSE_EQ | 10814 |   | IDFCFIRSTB | BOND 9% 2021 TR-1 SR-I | 5150 |   |   | 1 | 1 | EQUITY | INE092T08CK9
NSE_EQ | 10817 |   | IDFCFIRSTB | BOND 0% 2021 TR-1 SR-II | 11096 |   |   | 1 | 1 | EQUITY | INE092T08CL7
NSE_EQ | 10908 |   | IDFCFIRSTB | BOND 8.70% 2022 TR-2 SR-I |   |   |   | 1 | 1 | EQUITY | INE092T08CM5
NSE_EQ | 10914 |   | IDFCFIRSTB | BOND 0% 2022 TR-2 SR-II | 10680 |   |   | 1 | 1 | EQUITY | INE092T08CN3
NSE_EQ | 10917 |   | IDFCFIRSTB | BOND 8.43% 2022 TR-3 SR-I |   |   |   | 1 | 1 | EQUITY | INE092T08CO1
NSE_EQ | 10920 |   | IDFCFIRSTB | BOND 0% 2022 TR-3 SR-II |   |   |   | 1 | 1 | EQUITY | INE092T08CP8

As you can see here, symbol for the IDFCFIRSTB is same for bonds, How to get the feed for the Share since the name is same

**Comment by Rahulzz** [comment]
We hope this message finds you well. We would like to inform you that the issue you reported is related to an outdated version of our API. As a result, we will be closing this issue since it is no longer valid. We understand the importance of staying up-to-date, so we strongly urge you to start planning your migration towards the latest version, v2, of our API. As part of this process, please be aware that our legacy v1 API and SDK are scheduled for deprecation soon.

Exciting news! We are thrilled to announce the release of our brand new V2 API version, bringing along various improvements and enhancements. You can access it at https://upstox.com/uplink/

To ensure a smooth transition, we recommend obtaining the most recent SDK (v2.0.0) by visiting: https://pypi.org/project/upstox-python-sdk/

For your convenience, all the necessary details regarding the API's functionalities can be found in our comprehensive API documentation: https://upstox.com/developer/api-documentation/

We sincerely appreciate your cooperation during this transition period, and our dedicated team is ready to assist you with any queries or support you may need while using the latest version of our API.

Thank you for being part of the Upstox community, and we look forward to providing you with an even better experience with our v2 API.

Best regards,
The Upstox Team
