### ISSUE TITLE
Getting error while trying to cancel all the open orders.

### ISSUE THREAD

**Issue by droidShadow** [upstox/upstox-python#41]
Lately I have been getting following error, when I try to cancel all open orders in system.

```
  File "C:\Users\Admin\Anaconda3\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "E:\Work\Upstox\Final\AUTO_Order_cancellation.py", line 44, in order_cancel
    u.cancel_all_orders()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\upstox_api\api.py", line 610, in cancel_all_orders
    return self.api_call_helper('cancelAllOrders', PyCurlVerbs.DELETE, None, None)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\upstox_api\api.py", line 856, in api_call_helper
    raise requests.HTTPError(response.text)
requests.exceptions.HTTPError: {"code":400,"status":"Bad Request","timestamp":"2021-12-14T15:10:00+05:30","message":"No open orders to cancel","error":{"name":"Error","reason":"No open orders to cancel"}}``
```

I am using following code
```
u = Upstox(.....,access_token)
u.cancel_all_orders()
```

It is throwing error,  even though there are open orders present in the system.

Please look into this issue.

**Comment by Rahulzz** [comment]
We hope this message finds you well. We would like to inform you that the issue you reported is related to an outdated version of our API. As a result, we will be closing this issue since it is no longer valid. We understand the importance of staying up-to-date, so we strongly urge you to start planning your migration towards the latest version, v2, of our API. As part of this process, please be aware that our legacy v1 API and SDK are scheduled for deprecation soon.

Exciting news! We are thrilled to announce the release of our brand new V2 API version, bringing along various improvements and enhancements. You can access it at https://upstox.com/uplink/

To ensure a smooth transition, we recommend obtaining the most recent SDK (v2.0.0) by visiting: https://pypi.org/project/upstox-python-sdk/

For your convenience, all the necessary details regarding the API's functionalities can be found in our comprehensive API documentation: https://upstox.com/developer/api-documentation/

We sincerely appreciate your cooperation during this transition period, and our dedicated team is ready to assist you with any queries or support you may need while using the latest version of our API.

Thank you for being part of the Upstox community, and we look forward to providing you with an even better experience with our v2 API.

Best regards,
The Upstox Team
