### ISSUE TITLE
Error at accessing token

### ISSUE THREAD

**Issue by zzzzz0001** [upstox/upstox-python#42]
```
import upstox_api.api as upapi
s = upapi.Session (APIKEY)
s.set_redirect_uri (MYURL)
s.set_api_secret (APISECRET)

print (s.get_login_url())        #then I go into that website and log in which redirects to my website with the code

s.set_code ('p3VHsd')      #putting the code which i got

access_token = s.retrieve_access_token()       #this gives error
```
NOTE : i followed the code which has been given in this GitHub repo exactly
version of library -> 2.0.1
python version -> 3.9.13

ERROR
--------
SystemError                               Traceback (most recent call last)
Cell In[28], line 1
----> 1 access_token = s.retrieve_access_token()
      2 print ('Received access_token: %s' % access_token)

File [c:\Users\anaconda3\lib\site-packages\upstox_api\api.py:94](file:///C:/Users/anaconda3/lib/site-packages/upstox_api/api.py:94), in Session.retrieve_access_token(self)
     92 body = json.loads(r.text)
     93 if 'access_token' not in body:
---> 94     raise SystemError(body);
     95 return body

SystemError: {'message': 'Forbidden'}

**Comment by harinathselvaraj** [comment]
@zzzzz0001  I am facing the same issue. How did you fix it ?

**Comment by zzzzz0001** [comment]
@harinathselvaraj I fixed it already by not using this library and dealing with raw API myself.

**Comment by harinathselvaraj** [comment]
I tried the URLs - https://api-v2.upstox.com/login/authorization/token, https://api-v2.upstox.com/login/oauth/token, https://api.upstox.com/login/oauth/token but no luck. Can you please help me with a code snippet ?

________________________________

**Comment by zzzzz0001** [comment]
@harinathselvaraj Here is the link i use for the raw api and it does work. https://upstox.com/developer/api-documentation/

**Comment by tgvaibhav** [comment]
I am also getting the same error while using the upstox python lib.  
I went through the . https://upstox.com/developer/api-documentation/ and the url connection for auth :
https://api-v2.upstox.com/login/authorization/dialog?response_type=code&client_id=<Your-API-Key-Here>&redirect_uri=<Your-Redirect-URI-Here>&state=<Your-Optional-State-Parameter-Here>
1. What is State parameter I have to put?

**Comment by zzzzz0001** [comment]
@tgvaibhav @poorabJoshi I would really suggest you read the documentation properly, if you guys are new to API, please learn it properly as basic knowledge is needed to understand the documentation. So please stop using this library, this is an unmaintained library and it consumes the old API of upstox. So create your own custom functions for yourself by consuming raw API from the documentation. If you guys would like to test the API in an easy way, I would suggest you use HOPSCOTCH (the reason for this than Postman is that this is open source)

**Comment by ankurcoplug** [comment]
Hi @zzzzz0001 is it possible for you to share the steps? Please also elaborate on how to put redirect_api, I am using local flask server.

**Comment by harsh0520** [comment]
@zzzzz0001 were you able to execute the websocket implementation part. I tried a lot but could not make it work. I tried converting the javascript to python code using the various converting sites. All the converted codes use protobuf. Which gives error.

**Comment by Rahulzz** [comment]
Hi @harsh0520,

For the new Upstox v2 API, you can use the SDK by pulling the `v2.0.0` release. It provides access to the updated API functionalities.

Regarding your WebSocket question, we have shared a sample implementation in a different issue. You can find the response at this link: [https://github.com/upstox/upstox-python/issues/47#issuecomment-1628861286](https://github.com/upstox/upstox-python/issues/47#issuecomment-1628861286)

If you have any further questions, feel free to ask.

**Comment by Rahulzz** [comment]
We hope this message finds you well. We would like to inform you that the issue you reported is related to an outdated version of our API. As a result, we will be closing this issue since it is no longer valid. We understand the importance of staying up-to-date, so we strongly urge you to start planning your migration towards the latest version, v2, of our API. As part of this process, please be aware that our legacy v1 API and SDK are scheduled for deprecation soon.

Exciting news! We are thrilled to announce the release of our brand new V2 API version, bringing along various improvements and enhancements. You can access it at https://upstox.com/uplink/

To ensure a smooth transition, we recommend obtaining the most recent SDK (v2.0.0) by visiting: https://pypi.org/project/upstox-python-sdk/

For your convenience, all the necessary details regarding the API's functionalities can be found in our comprehensive API documentation: https://upstox.com/developer/api-documentation/

We sincerely appreciate your cooperation during this transition period, and our dedicated team is ready to assist you with any queries or support you may need while using the latest version of our API.

Thank you for being part of the Upstox community, and we look forward to providing you with an even better experience with our v2 API.

Best regards,
The Upstox Team
